# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idmService.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10idmService.proto\"9\n\x13\x43reateDoctorRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"H\n\x11UpdateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07id_user\x18\x03 \x01(\t\"F\n\x14\x43reateDoctorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07id_user\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"3\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"D\n\x12UpdateUserResponse\x12\x0f\n\x07id_user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"D\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\rTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\rSignUpRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"V\n\x0eSignUpResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x0f\n\x07id_user\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\x05\x32\xb8\x02\n\nIDMService\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12,\n\x0bVerifyToken\x12\r.TokenRequest\x1a\x0e.TokenResponse\x12)\n\x06SignUp\x12\x0e.SignUpRequest\x1a\x0f.SignUpResponse\x12;\n\x0c\x43reateDoctor\x12\x14.CreateDoctorRequest\x1a\x15.CreateDoctorResponse\x12\x35\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\x12\x35\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idmService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEDOCTORREQUEST']._serialized_start=20
  _globals['_CREATEDOCTORREQUEST']._serialized_end=77
  _globals['_DELETEUSERREQUEST']._serialized_start=79
  _globals['_DELETEUSERREQUEST']._serialized_end=115
  _globals['_UPDATEUSERREQUEST']._serialized_start=117
  _globals['_UPDATEUSERREQUEST']._serialized_end=189
  _globals['_CREATEDOCTORRESPONSE']._serialized_start=191
  _globals['_CREATEDOCTORRESPONSE']._serialized_end=261
  _globals['_DELETEUSERRESPONSE']._serialized_start=263
  _globals['_DELETEUSERRESPONSE']._serialized_end=314
  _globals['_UPDATEUSERRESPONSE']._serialized_start=316
  _globals['_UPDATEUSERRESPONSE']._serialized_end=384
  _globals['_LOGINREQUEST']._serialized_start=386
  _globals['_LOGINREQUEST']._serialized_end=436
  _globals['_LOGINRESPONSE']._serialized_start=438
  _globals['_LOGINRESPONSE']._serialized_end=506
  _globals['_TOKENREQUEST']._serialized_start=508
  _globals['_TOKENREQUEST']._serialized_end=537
  _globals['_TOKENRESPONSE']._serialized_start=539
  _globals['_TOKENRESPONSE']._serialized_end=589
  _globals['_SIGNUPREQUEST']._serialized_start=591
  _globals['_SIGNUPREQUEST']._serialized_end=642
  _globals['_SIGNUPRESPONSE']._serialized_start=644
  _globals['_SIGNUPRESPONSE']._serialized_end=730
  _globals['_IDMSERVICE']._serialized_start=733
  _globals['_IDMSERVICE']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
